# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: azure-search-openai-demo
metadata:
  template: azure-search-openai-demo@0.0.2-beta
services:
  backend:
    project: ./app/backend
    language: py
    host: appservice
    hooks:
      prepackage:
        windows:
          shell: pwsh
          run:  cd ../frontend;npm install;npm run build
          interactive: false
          continueOnError: false
        posix:
          shell: sh
          run:  cd ../frontend;npm install;npm run build
          interactive: false
          continueOnError: false
pipeline:
  variables:
      - AZURE_OPENAI_SERVICE
      - AZURE_OPENAI_API_VERSION
      - AZURE_OPENAI_RESOURCE_GROUP
      - AZURE_FORMRECOGNIZER_SERVICE
      - AZURE_FORMRECOGNIZER_RESOURCE_GROUP
      - AZURE_FORMRECOGNIZER_SKU
      - AZURE_SEARCH_INDEX
      - AZURE_SEARCH_SERVICE
      - AZURE_SEARCH_SERVICE_RESOURCE_GROUP
      - AZURE_SEARCH_SERVICE_LOCATION
      - AZURE_SEARCH_SERVICE_SKU
      - AZURE_SEARCH_QUERY_LANGUAGE
      - AZURE_SEARCH_QUERY_SPELLER
      - AZURE_SEARCH_SEMANTIC_RANKER
      - AZURE_STORAGE_ACCOUNT
      - AZURE_STORAGE_RESOURCE_GROUP
      - AZURE_STORAGE_SKU
      - AZURE_APP_SERVICE_SKU
      - AZURE_OPENAI_CHATGPT_MODEL
      - AZURE_OPENAI_CHATGPT_DEPLOYMENT
      - AZURE_OPENAI_CHATGPT_DEPLOYMENT_CAPACITY
      - AZURE_OPENAI_CHATGPT_DEPLOYMENT_VERSION
      - AZURE_OPENAI_EMB_MODEL_NAME
      - AZURE_OPENAI_EMB_DEPLOYMENT
      - AZURE_OPENAI_EMB_DEPLOYMENT_CAPACITY
      - AZURE_OPENAI_EMB_DEPLOYMENT_VERSION
      - OPENAI_HOST
      - OPENAI_API_KEY
      - OPENAI_ORGANIZATION
      - AZURE_USE_APPLICATION_INSIGHTS
      - USE_VECTORS
      - USE_GPT4V
      - AZURE_VISION_ENDPOINT
      - VISION_SECRET_NAME
      - AZURE_KEY_VAULT_NAME
      - AZURE_USE_AUTHENTICATION
      - AZURE_ENFORCE_ACCESS_CONTROL
      - AZURE_AUTH_TENANT_ID
      - AZURE_SERVER_APP_ID
      - AZURE_CLIENT_APP_ID
      - ALLOWED_ORIGIN
  secrets:
      - AZURE_SERVER_APP_SECRET
      - AZURE_CLIENT_APP_SECRET
hooks:
    preprovision:
      windows:
        shell: pwsh
        run: ./scripts/auth_init.ps1
        interactive: true
        continueOnError: false
      posix:
        shell: sh
        run: ./scripts/auth_init.sh
        interactive: true
        continueOnError: false
    postprovision:
      windows:
        shell: pwsh
        run: ./scripts/auth_update.ps1;./scripts/prepdocs.ps1
        interactive: true
        continueOnError: false
      posix:
        shell: sh
        run: ./scripts/auth_update.sh;./scripts/prepdocs.sh
        interactive: true
        continueOnError: false
