name: Frontend linting

on:
  push:
    branches: [ main ]
    paths:
      - "app/frontend/**"
  pull_request:
    branches: [ main ]
    paths:
      - "app/frontend/**"

jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Run prettier on frontend
              run: |
                cd ./app/frontend
                npm install
                npx prettier --check .
