name: Report Failure to Azure DevOps

on:
  workflow_run:
    workflows: ["ci.yml"]  # Replace with actual workflow name
    types:
      - completed

jobs:
  create_bug:
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Create Azure DevOps Bug
        uses: stefanstranger/azuredevops-bug-action@1.1
        with:
          OrganizationName: "https://dev.azure.com/rleme-001/"
          ProjectName: "azure-search-openai-demo"
          AreaPath: "azure-search-openai-demo\\General"
          IterationPath: "azure-search-openai-demo\\Sprint 1"
          GithubToken: "${{ secrets.GITHUB_TOKEN }}"
          WorkflowFileName: "azure-dev.yml"
        env:
          PAT: ${{ secrets.ADO_PAT }}
